name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_AUTH_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_AUTH_SERVICE_URL }}
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
          NEXT_PUBLIC_BOTS_CONNECTION_SECRET: ${{ secrets.NEXT_PUBLIC_BOTS_CONNECTION_SECRET }}
          NEXT_PUBLIC_MAIN_SERVICE_API_KEY: ${{ secrets.NEXT_PUBLIC_MAIN_SERVICE_API_KEY }}
          NEXT_PUBLIC_STATS_SERVICE_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_STATS_SERVICE_SECRET_KEY }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            # Переходим в директорию проекта
            cd /setup/neurox-frontend
            
            # Останавливаем приложение
            pm2 stop neurox || true
            
            # Получаем последние изменения
            git fetch origin main
            git reset --hard origin/main
            
            # Очищаем кеш npm для надежности
            npm cache clean --force
            
            # Устанавливаем зависимости
            npm ci --production
            
            # Создаем файл .env с переменными окружения
            cat > .env.production << EOF
            NEXT_PUBLIC_AUTH_SERVICE_URL=${{ secrets.NEXT_PUBLIC_AUTH_SERVICE_URL }}
            NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
            NEXT_PUBLIC_BOTS_CONNECTION_SECRET=${{ secrets.NEXT_PUBLIC_BOTS_CONNECTION_SECRET }}
            NEXT_PUBLIC_MAIN_SERVICE_API_KEY=${{ secrets.NEXT_PUBLIC_MAIN_SERVICE_API_KEY }}
            NEXT_PUBLIC_STATS_SERVICE_SECRET_KEY=${{ secrets.NEXT_PUBLIC_STATS_SERVICE_SECRET_KEY }}
            NODE_ENV=production
            EOF
            
            # Собираем проект
            npm run build
            
            # Запускаем приложение через PM2
            pm2 start npm --name "neurox" -- start
            
            # Сохраняем конфигурацию PM2
            pm2 save
            
            # Показываем статус
            pm2 status neurox